import { Craftsman, Category, Review } from "@/lib/types";

export const categories: Category[] = [
  { id: "1", name: "كهربائي",  icon: "Zap",        count: 128 },
  { id: "2", name: "سباك",     icon: "Wrench",      count: 95  },
  { id: "3", name: "نجار",     icon: "Hammer",      count: 76  },
  { id: "4", name: "دهان",     icon: "Paintbrush",  count: 112 },
  { id: "5", name: "بناء",     icon: "Building2",   count: 64  },
  { id: "6", name: "حداد",     icon: "Shield",      count: 43  },
  { id: "7", name: "مكيفات",   icon: "Wind",        count: 87  },
  { id: "8", name: "بلاط",     icon: "LayoutGrid",  count: 55  },
];

export const craftsmen: Craftsman[] = [
  {
    id: "1",
    name: "أحمد بن محمد",
    specialty: "كهربائي",
    rating: 4.9,
    reviewCount: 142,
    experience: 12,
    location: "الرياض",
    phone: "+966501234567",
    email: "ahmed@example.com",
    bio: "كهربائي محترف بخبرة تزيد عن 12 سنة في جميع أعمال الكهرباء المنزلية والتجارية. معتمد ومرخص.",
    services: [
      { name: "تمديدات كهربائية",  price: "150 ريال/ساعة" },
      { name: "صيانة لوحات التحكم",price: "200 ريال" },
      { name: "تركيب إضاءة",       price: "100 ريال" },
    ],
    featured: true,
    verified: true,
    avatar: "",
  },
  {
    id: "2",
    name: "محمد العلي",
    specialty: "سباك",
    rating: 4.7,
    reviewCount: 98,
    experience: 8,
    location: "جدة",
    phone: "+966507654321",
    email: "mohamed@example.com",
    bio: "متخصص في جميع أعمال السباكة والصرف الصحي. خدمة سريعة وموثوقة على مدار الساعة.",
    services: [
      { name: "إصلاح تسريبات",     price: "120 ريال" },
      { name: "تركيب أدوات صحية",  price: "180 ريال" },
      { name: "صيانة شبكات المياه", price: "250 ريال" },
    ],
    featured: true,
    verified: true,
    avatar: "",
  },
  {
    id: "3",
    name: "خالد الشمري",
    specialty: "نجار",
    rating: 4.8,
    reviewCount: 76,
    experience: 15,
    location: "الدمام",
    phone: "+966509876543",
    email: "khaled@example.com",
    bio: "نجار متميز متخصص في الأثاث المنزلي والمطابخ. تصاميم عصرية وخامات عالية الجودة.",
    services: [
      { name: "تصنيع مطابخ", price: "من 5000 ريال" },
      { name: "أثاث مخصص",  price: "حسب الطلب" },
      { name: "صيانة أبواب", price: "150 ريال" },
    ],
    featured: true,
    verified: false,
    avatar: "",
  },
  {
    id: "4",
    name: "عبدالله الحربي",
    specialty: "دهان",
    rating: 4.6,
    reviewCount: 54,
    experience: 10,
    location: "مكة",
    phone: "+966502345678",
    email: "abdullah@example.com",
    bio: "فنان دهان محترف. متخصص في الدهانات الديكورية والجرافيت والورق الجدران.",
    services: [
      { name: "دهان غرفة",   price: "من 800 ريال" },
      { name: "ورق جدران",   price: "من 500 ريال" },
      { name: "دهان خارجي", price: "حسب المساحة" },
    ],
    featured: false,
    verified: true,
    avatar: "",
  },
  {
    id: "5",
    name: "فهد القحطاني",
    specialty: "مكيفات",
    rating: 4.9,
    reviewCount: 200,
    experience: 14,
    location: "الرياض",
    phone: "+966508765432",
    email: "fahd@example.com",
    bio: "خبير في تركيب وصيانة جميع أنواع المكيفات. خدمة طوارئ على مدار الساعة.",
    services: [
      { name: "تركيب مكيف سبليت", price: "350 ريال" },
      { name: "صيانة دورية",       price: "150 ريال" },
      { name: "غسيل مكيفات",       price: "100 ريال" },
    ],
    featured: true,
    verified: true,
    avatar: "",
  },
  {
    id: "6",
    name: "سعد الدوسري",
    specialty: "بلاط",
    rating: 4.5,
    reviewCount: 38,
    experience: 7,
    location: "الخبر",
    phone: "+966503456789",
    email: "saad@example.com",
    bio: "متخصص في تركيب جميع أنواع البلاط والسيراميك والرخام بدقة عالية.",
    services: [
      { name: "تركيب بلاط", price: "40 ريال/م²" },
      { name: "رخام",        price: "80 ريال/م²" },
      { name: "بورسلان",     price: "50 ريال/م²" },
    ],
    featured: false,
    verified: true,
    avatar: "",
  },
];

export const reviews: Review[] = [
  { id: "1", craftsmanId: "1", userName: "عمر الفهد",     rating: 5, comment: "عمل ممتاز واحترافي. أنصح به بشدة!",          date: "2024-03-15" },
  { id: "2", craftsmanId: "1", userName: "سلطان المالكي", rating: 5, comment: "سريع وأمين. أفضل كهربائي تعاملت معه.",        date: "2024-03-10" },
  { id: "3", craftsmanId: "2", userName: "ناصر العتيبي",  rating: 4, comment: "خدمة جيدة وسعر مناسب.",                      date: "2024-03-12" },
  { id: "4", craftsmanId: "3", userName: "فيصل الرشيدي",  rating: 5, comment: "مطبخ رائع بتصميم عصري. شغل نظيف جداً.",     date: "2024-03-08" },
  { id: "5", craftsmanId: "5", userName: "يوسف الغامدي",  rating: 5, comment: "صيانة مكيف ممتازة. جاء في الموعد بالضبط.", date: "2024-03-14" },
];
